"""SYS handlers: pipeline.

Generated by the shard extraction. Each method self-registers on import
via @handles_sys(AstType). Composed into SystemExecutor as a mixin.
"""

from __future__ import annotations

import logging

import numpy as np

from supergraph.core.errors import SuperGraphError
from supergraph.core.types import Result
from supergraph.dsl.ast_nodes import (
    Condition,
)

logger = logging.getLogger(__name__)

from supergraph.dsl.ast_nodes import (
    SysConnect,
    SysConsolidate,
    SysDuplicates,
    SysEmbedders,
    SysReembed,
)
from supergraph.dsl.sys._registry import handles_sys


class SysPipelineHandlers:
    @handles_sys(SysDuplicates)
    def _duplicates(self, q: SysDuplicates) -> Result:
        """SYS DUPLICATES: find near-duplicate nodes by vector similarity."""
        vs = self._vector_store
        if vs is None or vs.count() == 0:
            return Result(kind="duplicates", data=[], count=0)

        store = self.store
        n = store._next_slot

        effective_threshold = q.threshold
        if self._duplicate_threshold_override is not None and q.threshold == 0.95:
            effective_threshold = self._duplicate_threshold_override

        mask = store.compute_live_mask(n)

        # Apply optional WHERE filter
        if q.where:
            expr = q.where.expr
            if isinstance(expr, Condition) and expr.field == "kind" and expr.op == "=":
                kind_mask = store._live_mask(expr.value)
                mask = mask & kind_mask

        # Collect slots that are both live and have vectors
        candidate_slots = []
        for slot in range(n):
            if mask[slot] and vs.has_vector(slot):
                candidate_slots.append(slot)

        if len(candidate_slots) < 2:
            return Result(kind="duplicates", data=[], count=0)

        # For each candidate, find its nearest neighbor among candidates
        seen = set()
        pairs = []
        candidate_mask = np.zeros(max(n, vs._capacity), dtype=bool)
        for s in candidate_slots:
            candidate_mask[s] = True

        for slot in candidate_slots:
            vec = vs.get_vector(slot)
            if vec is None:
                continue
            # Search for top-2 (first result may be self)
            slots_found, dists = vs.search(vec, k=2, mask=candidate_mask)
            for found_slot, dist in zip(slots_found, dists):
                found_slot = int(found_slot)
                if found_slot == slot:
                    continue
                # cosine similarity = 1 - cosine distance
                similarity = 1.0 - float(dist)
                if similarity >= effective_threshold:
                    pair_key = (min(slot, found_slot), max(slot, found_slot))
                    if pair_key not in seen:
                        seen.add(pair_key)
                        # Resolve IDs
                        id_a = store.string_table.lookup(int(store.node_ids[pair_key[0]]))
                        id_b = store.string_table.lookup(int(store.node_ids[pair_key[1]]))
                        pairs.append({
                            "node_a": id_a,
                            "node_b": id_b,
                            "similarity": round(similarity, 6),
                        })

        return Result(kind="duplicates", data=pairs, count=len(pairs))

    @handles_sys(SysEmbedders)
    def _embedders(self, q: SysEmbedders) -> Result:
        """SYS EMBEDDERS: list active embedder info."""
        info = []
        if self._embedder:
            info.append({
                "name": self._embedder.name,
                "dims": self._embedder.dims,
                "status": "active",
            })
        else:
            info.append({"name": "none", "status": "no embedder configured"})
        return Result(kind="embedders", data=info, count=len(info))

    @handles_sys(SysConnect)
    def _connect(self, q: SysConnect) -> Result:
        """SYS CONNECT: auto-wire cross-document relationships via vector similarity."""
        from supergraph.ingest.connector import connect_all
        return connect_all(
            self.store, self._vector_store,
            threshold=q.threshold, where_expr=q.where,
        )

    @handles_sys(SysConsolidate)
    def _consolidate(self, q: SysConsolidate) -> Result:
        """SYS CONSOLIDATE: cluster episodic memories into observations.

        Groups messages by entity (via 'mentions' edges), clusters by
        cosine similarity, creates 'observation' nodes with evidence links.
        No LLM required - picks the most representative message per cluster.
        """
        from supergraph.algos.consolidation import cluster_by_entity

        store = self.store
        n = store._next_slot
        live = store.compute_live_mask(n)

        # Build entity -> message slot mapping from graph edges
        entity_to_slots: dict[str, list[int]] = {}
        for etype, edge_list in store._edges_by_type.items():
            if etype != "mentions":
                continue
            for src_slot, tgt_slot, _data in edge_list:
                if not live[src_slot] or not live[tgt_slot]:
                    continue
                src_kind = store.string_table.lookup(int(store.node_kinds[src_slot]))
                if src_kind == "sentence":
                    for field in ("parent_node", "parent_chunk"):
                        col_info = store.columns.get_column(field, n)
                        if col_info is None:
                            continue
                        col_data, col_pres, _ = col_info
                        if not col_pres[src_slot]:
                            continue
                        parent_slot = store.id_to_slot.get(int(col_data[src_slot]))
                        if parent_slot is not None:
                            src_slot = int(parent_slot)
                            break
                entity_id = store._slot_to_id(tgt_slot)
                if entity_id:
                    slots = entity_to_slots.setdefault(entity_id, [])
                    if src_slot not in slots:
                        slots.append(src_slot)

        if not entity_to_slots:
            return Result(kind="ok", data={"observations": 0, "reason": "no entity edges found"}, count=0)

        # Gather texts
        texts: dict[int, str] = {}
        for entity_slots in entity_to_slots.values():
            for s in entity_slots:
                node = store._materialize_slot(s)
                if node:
                    texts[s] = node.get("content") or node.get("summary") or node.get("claim") or ""

        # Gather event times
        event_times: dict[int, int] = {}
        event_col = store.columns.get_column("__event_at__", n)
        if event_col is not None:
            col_data, col_pres, _ = event_col
            for slots in entity_to_slots.values():
                for s in slots:
                    if col_pres[s]:
                        event_times[s] = int(col_data[s])

        # Gather vectors
        vs = self._vector_store
        vectors = None
        has_vector = None
        if vs is not None:
            max_slot = max((s for slots in entity_to_slots.values() for s in slots), default=-1)
            if max_slot >= 0:
                cap = max_slot + 1
                vectors = np.zeros((cap, vs.dims), dtype=np.float32)
                has_vector = np.zeros(cap, dtype=bool)
                for slots in entity_to_slots.values():
                    for s in slots:
                        if s >= cap or not vs.has_vector(s):
                            continue
                        vec = vs.get_vector(s)
                        if vec is None:
                            continue
                        vectors[s] = vec
                        has_vector[s] = True

        observations = cluster_by_entity(
            entity_to_slots=entity_to_slots,
            vectors=vectors,
            has_vector=has_vector,
            texts=texts,
            event_times=event_times,
            similarity_threshold=q.similarity_threshold,
            min_cluster_size=q.min_cluster_size,
        )

        # Create observation nodes + evidence edges
        created = 0
        for i, obs in enumerate(observations):
            obs_id = f"obs:{obs.entity}:{i}"
            try:
                store.put_node(obs_id, "observation", {
                    "entity": obs.entity,
                    "content": obs.text,
                    "evidence_count": obs.evidence_count,
                })
                obs_slot = store.id_to_slot[store.string_table.intern(obs_id)]

                # Set confidence and event_at
                store.columns.set_reserved(obs_slot, "__confidence__", obs.confidence)
                if obs.event_at_ms is not None:
                    store.columns.set_reserved(obs_slot, "__event_at__", obs.event_at_ms)

                # Embed observation with cluster centroid
                if obs.centroid is not None and vs is not None:
                    vs.add(obs_slot, obs.centroid)

                # FTS index the observation text
                if self._document_store and obs.text:
                    self._document_store.put_summary(obs_slot, obs.text, doc_slot=0, chunk_index=0)

                # Link to evidence
                for ev_slot in obs.evidence_slots:
                    ev_id = store._slot_to_id(ev_slot)
                    if ev_id:
                        try:
                            store.put_edge(obs_id, ev_id, "evidence")
                        except Exception as err:
                            logger.debug("evidence edge %s -> %s skipped: %s", obs_id, ev_id, err)

                created += 1
            except Exception:
                continue

        return Result(kind="ok", data={
            "observations": created,
            "entities": len(entity_to_slots),
            "clusters": len(observations),
        }, count=created)

    @handles_sys(SysReembed)
    def _reembed(self, q: SysReembed) -> Result:
        """SYS REEMBED: re-encode EVERY embedder-produced vector with the current
        embedder, recovering each node's source text from the document store
        (DOCUMENT blob / summary), the legacy 'summary' column, or the kind's
        embed_field - not just the 'summary' column. Reports reembedded + skipped;
        the caller clears the embedder-dirty flag only when skipped == 0 (full
        coverage), so a swap never falsely reports all-clear while document
        vectors are left in the old embedder's space."""
        if not self._embedder:
            raise SuperGraphError("No embedder configured")

        vs = self._vector_store
        if vs is None:
            raise SuperGraphError("No vector store initialized")

        from supergraph.document.store import _is_text_content_type

        store = self.store
        ds = self._document_store
        schema = self.schema
        n = store._next_slot
        live = store.compute_live_mask(n)
        lookup = store.string_table.lookup

        summary_col = (
            store.columns.get_column("summary", n)
            if store.columns.has_column("summary") else None
        )

        def _col_text(col_info, slot):
            if col_info is None:
                return None
            data, pres, dtype = col_info
            if slot >= len(pres) or not pres[slot] or dtype != "int32_interned":
                return None
            return lookup(int(data[slot]))

        def _recover_text(slot):
            # priority mirrors how the vector was originally produced
            if ds is not None:
                doc = ds.get_document(slot)
                if doc is not None:
                    content, ctype = doc
                    if _is_text_content_type(ctype):
                        return content.decode("utf-8", errors="ignore")
                summ = ds.get_summary(slot)
                if summ and summ.get("summary"):
                    return summ["summary"]
            text = _col_text(summary_col, slot)
            if text:
                return text
            kind = lookup(int(store.node_kinds[slot]))
            kdef = schema.describe_node_kind(kind) if schema else None
            ef = kdef.get("embed_field") if kdef else None
            if ef and store.columns.has_column(ef):
                return _col_text(store.columns.get_column(ef, n), slot)
            return None

        pairs: list[tuple[int, str]] = []
        skipped = 0
        for slot in range(n):
            if not live[slot] or not vs.has_vector(slot):
                continue
            text = _recover_text(slot)
            if text:
                pairs.append((slot, text))
            else:
                skipped += 1

        if pairs:
            texts = [t for _, t in pairs]
            vecs = self._embedder.encode_documents(texts)
            for (slot, _), vec in zip(pairs, vecs):
                vs.add(slot, vec)

        # dirty flag cleared by the caller ONLY when skipped == 0 (full coverage)
        return Result(kind="ok", data={"reembedded": len(pairs), "skipped": skipped},
                      count=len(pairs))
