"""SYS handlers: queries.

Generated by the shard extraction. Each method self-registers on import
via @handles_sys(AstType). Composed into SystemExecutor as a mixin.
"""

from __future__ import annotations

import time
import logging

import numpy as np

from supergraph.core.errors import SuperGraphError, NodeNotFound
from supergraph.core.memory import estimate as estimate_memory
from supergraph.core.types import Result
from supergraph.dsl.ast_nodes import (
    Condition,
    MatchQuery,
    NodesQuery,
    RememberQuery,
    TraverseQuery,
)
from supergraph.dsl.cost_estimator import estimate_match_cost, estimate_traverse_cost

logger = logging.getLogger(__name__)

from supergraph.dsl.ast_nodes import (
    SysDescribe,
    SysEdgeKinds,
    SysExplain,
    SysFailedQueries,
    SysFrequentQueries,
    SysHealth,
    SysKinds,
    SysSlowQueries,
    SysSnapshots,
    SysStats,
    SysStatus,
)
from supergraph.dsl.sys._registry import handles_sys


class SysQueryHandlers:
    @handles_sys(SysStats)
    def _stats(self, q: SysStats) -> Result:
        data = {}
        if q.target is None or q.target == "NODES":
            data["node_count"] = self.store.node_count
        if q.target is None or q.target == "EDGES":
            data["edge_count"] = self.store.edge_count
            if q.target is None:
                data["edge_counts_by_type"] = {
                    etype: len(edges)
                    for etype, edges in self.store._edges_by_type.items()
                }
        if q.target is None or q.target == "MEMORY":
            data["memory_bytes"] = estimate_memory(
                self.store.node_count, self.store.edge_count
            )
            data["ceiling_bytes"] = self.store._ceiling_bytes
            data["column_memory_bytes"] = self.store.columns.memory_bytes
        if q.target is None or q.target == "WAL":
            if self.conn:
                row = self.conn.execute("SELECT COUNT(*) FROM wal").fetchone()
                data["wal_entries"] = row[0]
            else:
                data["wal_entries"] = 0
        if q.target is None:
            data["uptime_seconds"] = time.time() - self._start_time
        return Result(kind="stats", data=data, count=1)

    @handles_sys(SysKinds)
    def _kinds(self, q: SysKinds) -> Result:
        kinds = self.schema.list_node_kinds()
        return Result(kind="schema", data=kinds, count=len(kinds))

    @handles_sys(SysEdgeKinds)
    def _edge_kinds(self, q: SysEdgeKinds) -> Result:
        kinds = self.schema.list_edge_kinds()
        return Result(kind="schema", data=kinds, count=len(kinds))

    @handles_sys(SysDescribe)
    def _describe(self, q: SysDescribe) -> Result:
        if q.entity_type == "NODE":
            data = self.schema.describe_node_kind(q.name)
        else:
            data = self.schema.describe_edge_kind(q.name)
        return Result(kind="schema", data=data, count=1 if data else 0)

    @handles_sys(SysSlowQueries)
    def _slow_queries(self, q: SysSlowQueries) -> Result:
        if not self.conn:
            return Result(kind="log_entries", data=[], count=0)
        sql = "SELECT timestamp, query, elapsed_us, result_count, error FROM query_log"
        params: list = []
        if q.since:
            sql += " WHERE timestamp >= ?"
            import datetime

            dt = datetime.datetime.fromisoformat(q.since)
            params.append(dt.timestamp())
        sql += " ORDER BY elapsed_us DESC"
        if q.limit:
            sql += " LIMIT ?"
            params.append(q.limit.value)
        rows = self.conn.execute(sql, params).fetchall()
        entries = [
            {
                "timestamp": r[0],
                "query": r[1],
                "elapsed_us": r[2],
                "result_count": r[3],
                "error": r[4],
            }
            for r in rows
        ]
        return Result(kind="log_entries", data=entries, count=len(entries))

    @handles_sys(SysFrequentQueries)
    def _frequent_queries(self, q: SysFrequentQueries) -> Result:
        if not self.conn:
            return Result(kind="log_entries", data=[], count=0)
        sql = "SELECT query, COUNT(*) as cnt FROM query_log GROUP BY query ORDER BY cnt DESC"
        params: list = []
        if q.limit:
            sql += " LIMIT ?"
            params.append(q.limit.value)
        rows = self.conn.execute(sql, params).fetchall()
        entries = [{"query": r[0], "count": r[1]} for r in rows]
        return Result(kind="log_entries", data=entries, count=len(entries))

    @handles_sys(SysFailedQueries)
    def _failed_queries(self, q: SysFailedQueries) -> Result:
        if not self.conn:
            return Result(kind="log_entries", data=[], count=0)
            
        entries = []
        params: list = []
        if q.limit:
            params.append(q.limit.value)
            
        # 1. Fetch runtime query failures
        sql_log = (
            "SELECT timestamp, query, elapsed_us, error FROM query_log "
            "WHERE error IS NOT NULL ORDER BY timestamp DESC"
        )
        if q.limit:
            sql_log += " LIMIT ?"
        rows_log = self.conn.execute(sql_log, params).fetchall()
        for r in rows_log:
            entries.append({
                "source": "runtime",
                "timestamp": r[0],
                "query": r[1],
                "elapsed_us": r[2],
                "error": r[3],
            })
            
        # 2. Fetch recovery (WAL replay) failures
        sql_wal = "SELECT timestamp, statement, error_msg FROM failed_wal_entries ORDER BY timestamp DESC"
        if q.limit:
            sql_wal += " LIMIT ?"
        rows_wal = self.conn.execute(sql_wal, params).fetchall()
        for r in rows_wal:
            entries.append({
                "source": "recovery",
                "timestamp": r[0],
                "query": r[1],
                "elapsed_us": 0,
                "error": r[2],
            })
            
        entries.sort(key=lambda x: x["timestamp"], reverse=True)
        if q.limit:
            entries = entries[:q.limit.value]
            
        return Result(kind="log_entries", data=entries, count=len(entries))

    @handles_sys(SysExplain)
    def _explain(self, q: SysExplain) -> Result:
        """Run cost estimator / dry-run on the inner query without executing.

        For REMEMBER: delegates to the handler's ``_plan_only`` branch which
        runs gather + fuse + temporal filter and returns candidate slot ids
        with per-signal scores, skipping materialization, rerank, nucleus,
        and recall-count mutations.
        """
        inner = q.query
        if isinstance(inner, RememberQuery):
            if self._executor is None:
                return Result(
                    kind="plan",
                    data={"type": "direct", "note": "main executor not wired"},
                    count=1,
                )
            return self._executor._remember(inner, _plan_only=True)
        if isinstance(inner, MatchQuery):
            cost = estimate_match_cost(inner.pattern, self.store.edge_matrices)
        elif isinstance(inner, TraverseQuery):
            edge_type = None
            if inner.where:
                expr = inner.where.expr
                if (
                    isinstance(expr, Condition)
                    and expr.field == "kind"
                    and expr.op == "="
                ):
                    edge_type = expr.value
            cost = estimate_traverse_cost(
                inner.depth, self.store.edge_matrices, edge_type
            )
        elif isinstance(inner, NodesQuery):
            data = {"type": "scan", "estimated_nodes": self.store.node_count}
            if inner.where:
                expr = inner.where.expr
                if (
                    isinstance(expr, Condition)
                    and expr.field in self.store._indexed_fields
                ):
                    data["type"] = "index_lookup"
            return Result(kind="plan", data=data, count=1)
        else:
            return Result(
                kind="plan",
                data={
                    "type": "direct",
                    "note": "no cost estimation for this query type",
                },
                count=1,
            )

        return Result(kind="plan", data=cost.to_dict(), count=1)

    @handles_sys(SysStatus)
    def _status(self, q: SysStatus) -> Result:
        """SYS STATUS: comprehensive system state."""
        store = self.store
        data = {
            "nodes": store.node_count,
            "edges": store.edge_count,
            "memory_bytes": estimate_memory(store.node_count, store.edge_count),
            "ceiling_bytes": store._ceiling_bytes,
            "column_memory_bytes": store.columns.memory_bytes,
            "memory_measured": None,
        }

        # Vector store info
        vs = self._vector_store
        if vs is not None:
            data["vectors"] = {
                "count": vs.count(),
                "dims": vs.dims,
                "memory_bytes": vs.memory_bytes,
            }
        else:
            data["vectors"] = {"count": 0, "dims": 0, "memory_bytes": 0}

        # Embedder info
        if self._embedder:
            data["embedder"] = {
                "name": getattr(self._embedder, "name", "unknown"),
                "dims": getattr(self._embedder, "dims", 0),
                "status": "active",
            }
        else:
            data["embedder"] = {"name": "none", "status": "inactive"}

        # Document store info
        if self._document_store:
            try:
                data["documents"] = self._document_store.stats()
            except Exception as e:
                logger.debug("document store stats failed: %s", e, exc_info=True)
                data["documents"] = {}
        else:
            data["documents"] = {}

        # Edge types
        data["edge_types"] = {
            etype: len(edges)
            for etype, edges in store._edges_by_type.items()
        }

        # Schema info
        data["registered_kinds"] = self.schema.list_node_kinds()
        data["registered_edge_kinds"] = self.schema.list_edge_kinds()

        data["uptime_seconds"] = time.time() - self._start_time

        if self._wal_manager is not None:
            data["wal_replay_errors"] = self._wal_manager.replay_error_count
            if self._wal_manager.replay_error_count > 0:
                data["wal_replay_error_details"] = self._wal_manager.replay_errors

        # Accurate measurement (best-effort, failure leaves status without
        # memory_measured rather than failing SYS STATUS).
        try:
            from supergraph.core.memory import measure as measure_memory
            data["memory_measured"] = measure_memory(store, self._vector_store, self._document_store)
        except Exception as _mem_err:
            import logging as _logging
            _logging.getLogger(__name__).debug("SYS STATUS memory measure failed: %s", _mem_err)

        return Result(kind="status", data=data, count=1)

    @handles_sys(SysHealth)
    def _health(self, q: SysHealth) -> Result:
        """SYS HEALTH: pressure metrics for self-balancing decisions."""
        from supergraph.core.optimizer import health_check, needs_optimization
        health = health_check(self.store, self._vector_store, self._document_store)
        try:
            from supergraph.core.memory import measure as measure_memory
            mem = measure_memory(self.store, self._vector_store, self._document_store)
            health["memory_total"] = mem["total"]
            health["memory_ceiling"] = self.store._ceiling_bytes
            health["memory_utilization"] = round(mem["total"] / max(self.store._ceiling_bytes, 1), 3)
        except Exception as _mem_err:
            import logging as _logging
            _logging.getLogger(__name__).debug("SYS HEALTH memory measure failed: %s", _mem_err)
        health["recommended"] = needs_optimization(health)
        return Result(kind="health", data=health, count=1)

    @handles_sys(SysSnapshots)
    def _snapshots(self, q: SysSnapshots) -> Result:
        """SYS SNAPSHOTS: list all named snapshots."""
        names = list(self.store._snapshots.keys())
        return Result(kind="snapshots", data=names, count=len(names))
